# Database Configuration
database:
  host: localhost
  port: 5431
  user: restaurant_user
  password: restaurant_pass
  database: pizza

# RabbitMQ Configuration
rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest