version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: pizza-postgres
    environment:
      POSTGRES_DB: pizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5431"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: pizza-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_MANAGEMENT_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - ./rabbitdef/definitions.json:/etc/rabbitmq/definitions.json:ro

volumes:
  pgdata:
